Class {
	#name : #Chapter02,
	#superclass : #IPTLevel,
	#category : #InteractivePongTutorial
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/5/2024 09:40'
}
Chapter02 class >> ChapterLevel [
	^ {Level02. Level01}
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 16:54'
}
Chapter02 class >> ChapterName [
	^ 'Chapter02'
]
