Class {
	#name : #Introduction,
	#superclass : #IPTLevel,
	#category : #InteractivePongTutorial
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 12:55'
}
Introduction class >> ChapterLevel [
	^ {Level01}
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 12:55'
}
Introduction class >> ChapterName [
	^ 'Introduction'
]
