Class {
	#name : #IPTCodeVariant,
	#superclass : #Object,
	#instVars : [
		'levelNumber',
		'initialCode',
		'solutionCode'
	],
	#category : #InteractivePongTutorial
}

{
	#category : #accessing,
	#'squeak_changestamp' : 'Felix Knöfel 6/5/2024 11:40'
}
IPTCodeVariant >> initialCode [
	^ initialCode
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Felix Knöfel 6/5/2024 11:40'
}
IPTCodeVariant >> initialCode: anObject [
	initialCode := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Felix Knöfel 6/5/2024 11:43'
}
IPTCodeVariant >> levelNumber [
	^ levelNumber
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Felix Knöfel 6/5/2024 11:43'
}
IPTCodeVariant >> levelNumber: anObject [
	levelNumber := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Felix Knöfel 6/5/2024 11:40'
}
IPTCodeVariant >> solutionCode [
	^ solutionCode
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Felix Knöfel 6/5/2024 11:40'
}
IPTCodeVariant >> solutionCode: anObject [
	solutionCode := anObject
]
