Class {
	#name : #IPTLevel0201,
	#superclass : #IPTLevel,
	#category : #'InteractivePongTutorial-Levels'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'JZ 6/7/2024 14:14'
}
IPTLevel0201 >> chapterNumber [
	^ 2.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'JZ 6/7/2024 14:14'
}
IPTLevel0201 >> description [
	^'This is level 01 chapter 2'.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'JZ 6/7/2024 14:15'
}
IPTLevel0201 >> levelNumber [
	^ 201.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'JZ 6/7/2024 14:15'
}
IPTLevel0201 >> name [
	^ 'Chapter 2 Level01'.
]
