Class {
	#name : #IPTLevel0201,
	#superclass : #IPTLevel,
	#category : #'InteractivePongTutorial-Levels'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/11/2024 18:15'
}
IPTLevel0201 >> description [
	^ 'This is level 01 of chapter 2 :)'.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/11/2024 18:14'
}
IPTLevel0201 >> initialize [
	self 
		levelIndex: 1;
		name: 'C2Level01'.
	
]
