Class {
	#name : #IPTTestObject,
	#superclass : #Morph,
	#instVars : [
		'game',
		'speed'
	],
	#category : #'InteractivePongTutorial-Core'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 13:30'
}
IPTTestObject >> a [
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 13:31'
}
IPTTestObject >> aMethodWithParam: aParam [
"ichbinglucklich"
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 13:55'
}
IPTTestObject >> aMethodWithParam: aParam andAlso: aSecondParam [
"Ilalaadkakadjs"
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 13:32'
}
IPTTestObject >> aNormalMethod [
"ichbinnichttraurig"
]
