Class {
	#name : #IPTTestObject,
	#superclass : #Morph,
	#instVars : [
		'game',
		'speed'
	],
	#category : #'InteractivePongTutorial-Core'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 12:43'
}
IPTTestObject >> aMethodWithParam: aParam [

]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 12:37'
}
IPTTestObject >> aMethodWithParam: aParam andAlso: aSecondParam [

]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Felix Knöfel 6/12/2024 12:27'
}
IPTTestObject >> aNormalMethod [
sadnadnmas
]
