Class {
	#name : #Level02,
	#superclass : #Chapter02,
	#category : #InteractivePongTutorial
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 17:44'
}
Level02 class >> LevelName [
	^'Level02: some stuff'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 14:03'
}
Level02 >> LevelDescription [
	^'This is a Test explanation'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 14:01'
}
Level02 >> LevelName [
	^'Introduction'
]
