Class {
	#name : #Level01,
	#superclass : #Introduction,
	#category : #InteractivePongTutorial
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 17:43'
}
Level01 class >> LevelName [
	^'Level01: Introduction'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 14:03'
}
Level01 >> LevelDescription [
	^'This is a Test explanation'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Leo Sonnenberg 6/2/2024 14:01'
}
Level01 >> LevelName [
	^'Introduction'
]
